/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package search.condition.metadata.generator;

import org.junit.jupiter.api.Test;

import io.github.mainmethod0126.search.condition.metadata.generator.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
